"use strict";
exports.__esModule = true;
var message = "Hello Shashank";
var x = 10;
var y = 20;
var sum;
var title = "CodeEvolution";
var isBegginer = true;
var total = 23;
var name = "Neha";
var senetence = "My Name is " + name + "\nAnd I am a Beginner TypeScript Developer";
console.log(isBegginer);
console.log(senetence);
var n = null;
var u = undefined;
console.log(n);
var isNew = null;
var myName = undefined;
console.log(myName);
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ["Hello", 12];
console.log(list1);
console.log(person1);
