"use strict";
exports.__esModule = true;
var message = "Hello Shashank";
var x = 10;
var y = 20;
var sum;
var title = "CodeEvolution";
var isBegginer = true;
var total = 23;
var name = "Neha";
var senetence = "My Name is " + name + "\nAnd I am a Beginner TypeScript Developer";
console.log(isBegginer);
console.log(senetence);
